export const paths = {
    home: '/home',
    signin: '/signin',
    signup: '/signup',
    forgotPassword: '/forgot-password',
    profile: '/user/profile',
    selectRole: '/select-role',
    testPost: '/test',
    // Example of a dynamic route
    postDetail: (id: string) => `/posts/${id}`,
    jobDetail: (id: string) => `/jobs/${id}`,
};

export const apiPaths = {
    login: '/api/auth/login',
    signup: '/api/auth/signup',
    getPosts: '/api/posts',
    getProfilePost: '/posts/myPost',
    uploadFile: '/posts/uploads',
    getTest: '/posts/test',
    checkAccessCompany: '/companies/',
    createPost: '/posts/create',
    updatePost: '/posts/update',
    deletePost: '/posts/delete',
    getJobByCompanyId: '/jobs/myJob',
    createJob: '/jobs/create',
    deleteJob: '/jobs/delete',
    getCompanyJobDetail: '/jobs/detail',
    getJobByStatus: '/jobs/status',
    getCandidateByStatus: '/jobs/candidates',
    getGlobalSearch: '/search/globalSearch',
    feedBackCandidate: '/jobs/feedback',
    applyJob: 'jobs/apply',
    updateCompanyJob: '/jobs/update',
    likePost: '/posts/like',
    unLikePost: '/posts/unlike',
    listLikePost: '/posts/like/list',
    getVideo: '/posts/video',
    createComment: '/posts/comment/create',
    getCommentById: '/posts/comment',
    getAllComment: '/posts/comment/list',
    getPostById: (id: string) => `/api/posts/${id}`,
    getFeed: '/feed',
};
